require: rubocop-rails
Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'config/environments/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/application.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/telegram_controller.rb'
    -
AllCops:
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - bin/*