require: rubocop-rails
Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'config/environments/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/application.rb'